export enum ErrorType {
  OverFlow = 'OverFlow',
  Mod2ShouldZero = 'Mod2ShouldZero',
  Mod4ShouldOne = 'Mod4ShouldOne',
  OutOfRange = 'OutOfRange',
  SumShouldEqW = 'SumShouldEqW',
  PolyError = 'PolyError',
  CompressError = 'CompressError',
  KemError = 'KemError',
  InvalidRqChunkSize = 'InvalidRqChunkSize',
  SyncThreadJoinError = 'SyncThreadJoinError',
  SyncLockError = 'SyncLockError',
  NoSolutionRecip3 = 'NoSolutionRecip3',
  R3NoSolutionRecip = 'R3NoSolutionRecip',
  SliceLengthNotR3Size = 'SliceLengthNotR3Size',
  SeedSliceError = 'SeedSliceError',
  SizeSliceError = 'SizeSliceError',
  ByteslengthError = 'ByteslengthError',
  InvalidR3GInvrBytes = 'InvalidR3GInvrBytes',
  InvalidR3FBytes = 'InvalidR3FBytes'
}
